source 'http://ruby.taobao.org'

gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

# frontend dependences
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'compass-rails'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'mongoid'
gem 'bson_ext'

gem 'settingslogic'
gem 'inherited_resources'

group :development, :test do
  gem 'thin'
  gem 'spring'
  gem 'pry-rails'
  gem 'pry-nav'
  gem "quiet_assets"
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'awesome_print'
  gem 'factory_girl_rails'
end


gem 'grape'
gem 'grape-jbuilder'
gem 'rack-cors'  #solve the CORS problem
gem 'swagger-ui_rails'
gem 'grape-swagger-rails' # autogenerated documentation for grape-API.
